/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExampleRouteImport } from './routes/example'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWalletsRouteImport } from './routes/_authenticated/wallets'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as ApiWalletsIndexRouteImport } from './routes/api/wallets/index'
import { Route as ApiUsersIndexRouteImport } from './routes/api/users/index'
import { Route as ApiCustomersIndexRouteImport } from './routes/api/customers/index'
import { Route as ApiWalletsIdRouteImport } from './routes/api/wallets/[id]'
import { Route as ApiUsersIdRouteImport } from './routes/api/users/$id'
import { Route as ApiDashboardMetricsRouteImport } from './routes/api/dashboard/metrics'
import { Route as ApiCustomersIdRouteImport } from './routes/api/customers/[id]'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as AuthenticatedWalletsIdRouteImport } from './routes/_authenticated/wallets.$id'
import { Route as AuthenticatedCustomersIdRouteImport } from './routes/_authenticated/customers.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleRoute = ExampleRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletsRoute = AuthenticatedWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiWalletsIndexRoute = ApiWalletsIndexRouteImport.update({
  id: '/api/wallets/',
  path: '/api/wallets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersIndexRoute = ApiUsersIndexRouteImport.update({
  id: '/api/users/',
  path: '/api/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomersIndexRoute = ApiCustomersIndexRouteImport.update({
  id: '/api/customers/',
  path: '/api/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalletsIdRoute = ApiWalletsIdRouteImport.update({
  id: '/api/wallets/id',
  path: '/api/wallets/id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/api/users/$id',
  path: '/api/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardMetricsRoute = ApiDashboardMetricsRouteImport.update({
  id: '/api/dashboard/metrics',
  path: '/api/dashboard/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomersIdRoute = ApiCustomersIdRouteImport.update({
  id: '/api/customers/id',
  path: '/api/customers/id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletsIdRoute = AuthenticatedWalletsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedWalletsRoute,
} as any)
const AuthenticatedCustomersIdRoute =
  AuthenticatedCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/example': typeof ExampleRoute
  '/login': typeof LoginRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/wallets': typeof AuthenticatedWalletsRouteWithChildren
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/wallets/$id': typeof AuthenticatedWalletsIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/customers/id': typeof ApiCustomersIdRoute
  '/api/dashboard/metrics': typeof ApiDashboardMetricsRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/wallets/id': typeof ApiWalletsIdRoute
  '/api/customers': typeof ApiCustomersIndexRoute
  '/api/users': typeof ApiUsersIndexRoute
  '/api/wallets': typeof ApiWalletsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/example': typeof ExampleRoute
  '/login': typeof LoginRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/wallets': typeof AuthenticatedWalletsRouteWithChildren
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/wallets/$id': typeof AuthenticatedWalletsIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/customers/id': typeof ApiCustomersIdRoute
  '/api/dashboard/metrics': typeof ApiDashboardMetricsRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/wallets/id': typeof ApiWalletsIdRoute
  '/api/customers': typeof ApiCustomersIndexRoute
  '/api/users': typeof ApiUsersIndexRoute
  '/api/wallets': typeof ApiWalletsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/example': typeof ExampleRoute
  '/login': typeof LoginRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/wallets': typeof AuthenticatedWalletsRouteWithChildren
  '/_authenticated/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/_authenticated/wallets/$id': typeof AuthenticatedWalletsIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/customers/id': typeof ApiCustomersIdRoute
  '/api/dashboard/metrics': typeof ApiDashboardMetricsRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/wallets/id': typeof ApiWalletsIdRoute
  '/api/customers/': typeof ApiCustomersIndexRoute
  '/api/users/': typeof ApiUsersIndexRoute
  '/api/wallets/': typeof ApiWalletsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/example'
    | '/login'
    | '/customers'
    | '/dashboard'
    | '/wallets'
    | '/customers/$id'
    | '/wallets/$id'
    | '/api/auth/login'
    | '/api/customers/id'
    | '/api/dashboard/metrics'
    | '/api/users/$id'
    | '/api/wallets/id'
    | '/api/customers'
    | '/api/users'
    | '/api/wallets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/example'
    | '/login'
    | '/customers'
    | '/dashboard'
    | '/wallets'
    | '/customers/$id'
    | '/wallets/$id'
    | '/api/auth/login'
    | '/api/customers/id'
    | '/api/dashboard/metrics'
    | '/api/users/$id'
    | '/api/wallets/id'
    | '/api/customers'
    | '/api/users'
    | '/api/wallets'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/example'
    | '/login'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/wallets'
    | '/_authenticated/customers/$id'
    | '/_authenticated/wallets/$id'
    | '/api/auth/login'
    | '/api/customers/id'
    | '/api/dashboard/metrics'
    | '/api/users/$id'
    | '/api/wallets/id'
    | '/api/customers/'
    | '/api/users/'
    | '/api/wallets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ExampleRoute: typeof ExampleRoute
  LoginRoute: typeof LoginRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiCustomersIdRoute: typeof ApiCustomersIdRoute
  ApiDashboardMetricsRoute: typeof ApiDashboardMetricsRoute
  ApiUsersIdRoute: typeof ApiUsersIdRoute
  ApiWalletsIdRoute: typeof ApiWalletsIdRoute
  ApiCustomersIndexRoute: typeof ApiCustomersIndexRoute
  ApiUsersIndexRoute: typeof ApiUsersIndexRoute
  ApiWalletsIndexRoute: typeof ApiWalletsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example': {
      id: '/example'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof ExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallets': {
      id: '/_authenticated/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof AuthenticatedWalletsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/wallets/': {
      id: '/api/wallets/'
      path: '/api/wallets'
      fullPath: '/api/wallets'
      preLoaderRoute: typeof ApiWalletsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/': {
      id: '/api/users/'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customers/': {
      id: '/api/customers/'
      path: '/api/customers'
      fullPath: '/api/customers'
      preLoaderRoute: typeof ApiCustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallets/id': {
      id: '/api/wallets/id'
      path: '/api/wallets/id'
      fullPath: '/api/wallets/id'
      preLoaderRoute: typeof ApiWalletsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/api/users/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/metrics': {
      id: '/api/dashboard/metrics'
      path: '/api/dashboard/metrics'
      fullPath: '/api/dashboard/metrics'
      preLoaderRoute: typeof ApiDashboardMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customers/id': {
      id: '/api/customers/id'
      path: '/api/customers/id'
      fullPath: '/api/customers/id'
      preLoaderRoute: typeof ApiCustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallets/$id': {
      id: '/_authenticated/wallets/$id'
      path: '/$id'
      fullPath: '/wallets/$id'
      preLoaderRoute: typeof AuthenticatedWalletsIdRouteImport
      parentRoute: typeof AuthenticatedWalletsRoute
    }
    '/_authenticated/customers/$id': {
      id: '/_authenticated/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersIdRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
  }
}

interface AuthenticatedCustomersRouteChildren {
  AuthenticatedCustomersIdRoute: typeof AuthenticatedCustomersIdRoute
}

const AuthenticatedCustomersRouteChildren: AuthenticatedCustomersRouteChildren =
  {
    AuthenticatedCustomersIdRoute: AuthenticatedCustomersIdRoute,
  }

const AuthenticatedCustomersRouteWithChildren =
  AuthenticatedCustomersRoute._addFileChildren(
    AuthenticatedCustomersRouteChildren,
  )

interface AuthenticatedWalletsRouteChildren {
  AuthenticatedWalletsIdRoute: typeof AuthenticatedWalletsIdRoute
}

const AuthenticatedWalletsRouteChildren: AuthenticatedWalletsRouteChildren = {
  AuthenticatedWalletsIdRoute: AuthenticatedWalletsIdRoute,
}

const AuthenticatedWalletsRouteWithChildren =
  AuthenticatedWalletsRoute._addFileChildren(AuthenticatedWalletsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedWalletsRoute: typeof AuthenticatedWalletsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCustomersRoute: AuthenticatedCustomersRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedWalletsRoute: AuthenticatedWalletsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ExampleRoute: ExampleRoute,
  LoginRoute: LoginRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiCustomersIdRoute: ApiCustomersIdRoute,
  ApiDashboardMetricsRoute: ApiDashboardMetricsRoute,
  ApiUsersIdRoute: ApiUsersIdRoute,
  ApiWalletsIdRoute: ApiWalletsIdRoute,
  ApiCustomersIndexRoute: ApiCustomersIndexRoute,
  ApiUsersIndexRoute: ApiUsersIndexRoute,
  ApiWalletsIndexRoute: ApiWalletsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
