/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExampleRouteImport } from './routes/example'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiWalletsIndexRouteImport } from './routes/api/wallets/index'
import { Route as ApiUsersIndexRouteImport } from './routes/api/users/index'
import { Route as ApiCustomersIndexRouteImport } from './routes/api/customers/index'
import { Route as AuthenticatedWalletsIndexRouteImport } from './routes/_authenticated/wallets.index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers.index'
import { Route as ApiWalletsIdRouteImport } from './routes/api/wallets/$id'
import { Route as ApiUsersIdRouteImport } from './routes/api/users/$id'
import { Route as ApiDashboardMetricsRouteImport } from './routes/api/dashboard/metrics'
import { Route as ApiCustomersIdRouteImport } from './routes/api/customers/[id]'
import { Route as ApiAuthValidateTokenRouteImport } from './routes/api/auth/validate-token'
import { Route as ApiAuthSubAccountsRouteImport } from './routes/api/auth/sub-accounts'
import { Route as AuthenticatedWalletsIdRouteImport } from './routes/_authenticated/wallets.$id'
import { Route as AuthenticatedCustomersIdRouteImport } from './routes/_authenticated/customers.$id'
import { Route as ApiWalletsIdWithdrawalsRouteImport } from './routes/api/wallets/$id/withdrawals'
import { Route as ApiWalletsIdTransfersRouteImport } from './routes/api/wallets/$id/transfers'
import { Route as ApiWalletsIdDepositsRouteImport } from './routes/api/wallets/$id/deposits'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleRoute = ExampleRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiWalletsIndexRoute = ApiWalletsIndexRouteImport.update({
  id: '/api/wallets/',
  path: '/api/wallets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersIndexRoute = ApiUsersIndexRouteImport.update({
  id: '/api/users/',
  path: '/api/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomersIndexRoute = ApiCustomersIndexRouteImport.update({
  id: '/api/customers/',
  path: '/api/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletsIndexRoute =
  AuthenticatedWalletsIndexRouteImport.update({
    id: '/wallets/',
    path: '/wallets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiWalletsIdRoute = ApiWalletsIdRouteImport.update({
  id: '/api/wallets/$id',
  path: '/api/wallets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/api/users/$id',
  path: '/api/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardMetricsRoute = ApiDashboardMetricsRouteImport.update({
  id: '/api/dashboard/metrics',
  path: '/api/dashboard/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomersIdRoute = ApiCustomersIdRouteImport.update({
  id: '/api/customers/id',
  path: '/api/customers/id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthValidateTokenRoute = ApiAuthValidateTokenRouteImport.update({
  id: '/api/auth/validate-token',
  path: '/api/auth/validate-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSubAccountsRoute = ApiAuthSubAccountsRouteImport.update({
  id: '/api/auth/sub-accounts',
  path: '/api/auth/sub-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletsIdRoute = AuthenticatedWalletsIdRouteImport.update({
  id: '/wallets/$id',
  path: '/wallets/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersIdRoute =
  AuthenticatedCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiWalletsIdWithdrawalsRoute = ApiWalletsIdWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => ApiWalletsIdRoute,
} as any)
const ApiWalletsIdTransfersRoute = ApiWalletsIdTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => ApiWalletsIdRoute,
} as any)
const ApiWalletsIdDepositsRoute = ApiWalletsIdDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => ApiWalletsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/example': typeof ExampleRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/wallets/$id': typeof AuthenticatedWalletsIdRoute
  '/api/auth/sub-accounts': typeof ApiAuthSubAccountsRoute
  '/api/auth/validate-token': typeof ApiAuthValidateTokenRoute
  '/api/customers/id': typeof ApiCustomersIdRoute
  '/api/dashboard/metrics': typeof ApiDashboardMetricsRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/wallets/$id': typeof ApiWalletsIdRouteWithChildren
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/wallets': typeof AuthenticatedWalletsIndexRoute
  '/api/customers': typeof ApiCustomersIndexRoute
  '/api/users': typeof ApiUsersIndexRoute
  '/api/wallets': typeof ApiWalletsIndexRoute
  '/api/wallets/$id/deposits': typeof ApiWalletsIdDepositsRoute
  '/api/wallets/$id/transfers': typeof ApiWalletsIdTransfersRoute
  '/api/wallets/$id/withdrawals': typeof ApiWalletsIdWithdrawalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/example': typeof ExampleRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/wallets/$id': typeof AuthenticatedWalletsIdRoute
  '/api/auth/sub-accounts': typeof ApiAuthSubAccountsRoute
  '/api/auth/validate-token': typeof ApiAuthValidateTokenRoute
  '/api/customers/id': typeof ApiCustomersIdRoute
  '/api/dashboard/metrics': typeof ApiDashboardMetricsRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/wallets/$id': typeof ApiWalletsIdRouteWithChildren
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/wallets': typeof AuthenticatedWalletsIndexRoute
  '/api/customers': typeof ApiCustomersIndexRoute
  '/api/users': typeof ApiUsersIndexRoute
  '/api/wallets': typeof ApiWalletsIndexRoute
  '/api/wallets/$id/deposits': typeof ApiWalletsIdDepositsRoute
  '/api/wallets/$id/transfers': typeof ApiWalletsIdTransfersRoute
  '/api/wallets/$id/withdrawals': typeof ApiWalletsIdWithdrawalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/example': typeof ExampleRoute
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/_authenticated/wallets/$id': typeof AuthenticatedWalletsIdRoute
  '/api/auth/sub-accounts': typeof ApiAuthSubAccountsRoute
  '/api/auth/validate-token': typeof ApiAuthValidateTokenRoute
  '/api/customers/id': typeof ApiCustomersIdRoute
  '/api/dashboard/metrics': typeof ApiDashboardMetricsRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/wallets/$id': typeof ApiWalletsIdRouteWithChildren
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/wallets/': typeof AuthenticatedWalletsIndexRoute
  '/api/customers/': typeof ApiCustomersIndexRoute
  '/api/users/': typeof ApiUsersIndexRoute
  '/api/wallets/': typeof ApiWalletsIndexRoute
  '/api/wallets/$id/deposits': typeof ApiWalletsIdDepositsRoute
  '/api/wallets/$id/transfers': typeof ApiWalletsIdTransfersRoute
  '/api/wallets/$id/withdrawals': typeof ApiWalletsIdWithdrawalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/example'
    | '/login'
    | '/dashboard'
    | '/customers/$id'
    | '/wallets/$id'
    | '/api/auth/sub-accounts'
    | '/api/auth/validate-token'
    | '/api/customers/id'
    | '/api/dashboard/metrics'
    | '/api/users/$id'
    | '/api/wallets/$id'
    | '/customers'
    | '/wallets'
    | '/api/customers'
    | '/api/users'
    | '/api/wallets'
    | '/api/wallets/$id/deposits'
    | '/api/wallets/$id/transfers'
    | '/api/wallets/$id/withdrawals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/example'
    | '/login'
    | '/dashboard'
    | '/customers/$id'
    | '/wallets/$id'
    | '/api/auth/sub-accounts'
    | '/api/auth/validate-token'
    | '/api/customers/id'
    | '/api/dashboard/metrics'
    | '/api/users/$id'
    | '/api/wallets/$id'
    | '/customers'
    | '/wallets'
    | '/api/customers'
    | '/api/users'
    | '/api/wallets'
    | '/api/wallets/$id/deposits'
    | '/api/wallets/$id/transfers'
    | '/api/wallets/$id/withdrawals'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/example'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/customers/$id'
    | '/_authenticated/wallets/$id'
    | '/api/auth/sub-accounts'
    | '/api/auth/validate-token'
    | '/api/customers/id'
    | '/api/dashboard/metrics'
    | '/api/users/$id'
    | '/api/wallets/$id'
    | '/_authenticated/customers/'
    | '/_authenticated/wallets/'
    | '/api/customers/'
    | '/api/users/'
    | '/api/wallets/'
    | '/api/wallets/$id/deposits'
    | '/api/wallets/$id/transfers'
    | '/api/wallets/$id/withdrawals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ExampleRoute: typeof ExampleRoute
  LoginRoute: typeof LoginRoute
  ApiAuthSubAccountsRoute: typeof ApiAuthSubAccountsRoute
  ApiAuthValidateTokenRoute: typeof ApiAuthValidateTokenRoute
  ApiCustomersIdRoute: typeof ApiCustomersIdRoute
  ApiDashboardMetricsRoute: typeof ApiDashboardMetricsRoute
  ApiUsersIdRoute: typeof ApiUsersIdRoute
  ApiWalletsIdRoute: typeof ApiWalletsIdRouteWithChildren
  ApiCustomersIndexRoute: typeof ApiCustomersIndexRoute
  ApiUsersIndexRoute: typeof ApiUsersIndexRoute
  ApiWalletsIndexRoute: typeof ApiWalletsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example': {
      id: '/example'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof ExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/wallets/': {
      id: '/api/wallets/'
      path: '/api/wallets'
      fullPath: '/api/wallets'
      preLoaderRoute: typeof ApiWalletsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/': {
      id: '/api/users/'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customers/': {
      id: '/api/customers/'
      path: '/api/customers'
      fullPath: '/api/customers'
      preLoaderRoute: typeof ApiCustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallets/': {
      id: '/_authenticated/wallets/'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof AuthenticatedWalletsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/wallets/$id': {
      id: '/api/wallets/$id'
      path: '/api/wallets/$id'
      fullPath: '/api/wallets/$id'
      preLoaderRoute: typeof ApiWalletsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/api/users/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/metrics': {
      id: '/api/dashboard/metrics'
      path: '/api/dashboard/metrics'
      fullPath: '/api/dashboard/metrics'
      preLoaderRoute: typeof ApiDashboardMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customers/id': {
      id: '/api/customers/id'
      path: '/api/customers/id'
      fullPath: '/api/customers/id'
      preLoaderRoute: typeof ApiCustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/validate-token': {
      id: '/api/auth/validate-token'
      path: '/api/auth/validate-token'
      fullPath: '/api/auth/validate-token'
      preLoaderRoute: typeof ApiAuthValidateTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sub-accounts': {
      id: '/api/auth/sub-accounts'
      path: '/api/auth/sub-accounts'
      fullPath: '/api/auth/sub-accounts'
      preLoaderRoute: typeof ApiAuthSubAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallets/$id': {
      id: '/_authenticated/wallets/$id'
      path: '/wallets/$id'
      fullPath: '/wallets/$id'
      preLoaderRoute: typeof AuthenticatedWalletsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/$id': {
      id: '/_authenticated/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/wallets/$id/withdrawals': {
      id: '/api/wallets/$id/withdrawals'
      path: '/withdrawals'
      fullPath: '/api/wallets/$id/withdrawals'
      preLoaderRoute: typeof ApiWalletsIdWithdrawalsRouteImport
      parentRoute: typeof ApiWalletsIdRoute
    }
    '/api/wallets/$id/transfers': {
      id: '/api/wallets/$id/transfers'
      path: '/transfers'
      fullPath: '/api/wallets/$id/transfers'
      preLoaderRoute: typeof ApiWalletsIdTransfersRouteImport
      parentRoute: typeof ApiWalletsIdRoute
    }
    '/api/wallets/$id/deposits': {
      id: '/api/wallets/$id/deposits'
      path: '/deposits'
      fullPath: '/api/wallets/$id/deposits'
      preLoaderRoute: typeof ApiWalletsIdDepositsRouteImport
      parentRoute: typeof ApiWalletsIdRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedCustomersIdRoute: typeof AuthenticatedCustomersIdRoute
  AuthenticatedWalletsIdRoute: typeof AuthenticatedWalletsIdRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedWalletsIndexRoute: typeof AuthenticatedWalletsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedCustomersIdRoute: AuthenticatedCustomersIdRoute,
  AuthenticatedWalletsIdRoute: AuthenticatedWalletsIdRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedWalletsIndexRoute: AuthenticatedWalletsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiWalletsIdRouteChildren {
  ApiWalletsIdDepositsRoute: typeof ApiWalletsIdDepositsRoute
  ApiWalletsIdTransfersRoute: typeof ApiWalletsIdTransfersRoute
  ApiWalletsIdWithdrawalsRoute: typeof ApiWalletsIdWithdrawalsRoute
}

const ApiWalletsIdRouteChildren: ApiWalletsIdRouteChildren = {
  ApiWalletsIdDepositsRoute: ApiWalletsIdDepositsRoute,
  ApiWalletsIdTransfersRoute: ApiWalletsIdTransfersRoute,
  ApiWalletsIdWithdrawalsRoute: ApiWalletsIdWithdrawalsRoute,
}

const ApiWalletsIdRouteWithChildren = ApiWalletsIdRoute._addFileChildren(
  ApiWalletsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ExampleRoute: ExampleRoute,
  LoginRoute: LoginRoute,
  ApiAuthSubAccountsRoute: ApiAuthSubAccountsRoute,
  ApiAuthValidateTokenRoute: ApiAuthValidateTokenRoute,
  ApiCustomersIdRoute: ApiCustomersIdRoute,
  ApiDashboardMetricsRoute: ApiDashboardMetricsRoute,
  ApiUsersIdRoute: ApiUsersIdRoute,
  ApiWalletsIdRoute: ApiWalletsIdRouteWithChildren,
  ApiCustomersIndexRoute: ApiCustomersIndexRoute,
  ApiUsersIndexRoute: ApiUsersIndexRoute,
  ApiWalletsIndexRoute: ApiWalletsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
